version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8083:8083"  # Порт для uvicorn
      - "5556:5556"  # Порт для Flower
    volumes:
      - .:/app  # Монтирование текущей директории для доступа к проекту
      - ./env_files/.env:/app/.env:ro  # Монтирование файла .env как только для чтения
    environment:
      - TZ=Asia/Yekaterinburg  # Установка часового пояса
    command: ["supervisord", "-c", "/etc/supervisord.conf"]
